force-app/main/default/objects/Industry_Priority__mdt/Industry_Priority__mdt.object-meta.xml
<CustomObject>
    <label>Industry Priority</label>
    <pluralLabel>Industry Priorities</pluralLabel>
</CustomObject>

force-app/main/default/objects/Industry_Priority__mdt/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Industry_Priority__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Prioritized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Prioritized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityServiceV2_TEST.cls
@isTest
public with sharing class OpportunityServiceV2_TEST {
    private class MockQueryDelegate implements OpportunityServiceV2.IOppServiceQueryDelegate {
        public List<Industry_Priority__mdt> getPriorityMetadata() {
            return new List<Industry_Priority__mdt>{
                new Industry_Priority__mdt(
                    Priority__c = 'Prioritized',
                    Industry__c = 'Spaceflight'
                )
            };
        }
    }

    @testSetup
    public static void setup() {
        insert new List<Account> {
            new Account(Name = 'Mao-Kwikowski Mercantile', Industry = 'Spaceflight'),
            new Account(Name = 'Protogen Corp.', Industry = 'Nanobiology'),
            new Account(Name = 'Beratnas Gas', Industry = 'Mining')
        };
    }

    @isTest
    public static void test_v2_sets_priority_from_custom_metadata() {
        Opportunity o = new Opportunity(
            AccountId = [SELECT Id FROM Account WHERE Industry = 'Spaceflight'].Id,
            Name = 'Expansive Deal',
            CloseDate = Date.today(),
            StageName = 'New'
        );
        OpportunityServiceV2 os = new OpportunityServiceV2();

        os.delegate = new MockQueryDelegate();

        Test.startTest();
        os.updatePriorities_v2(new List<Opportunity>{o}, OpportunityServiceV2.OpportunityMode.MODE_OVERWRITE);
        Test.stopTest();

        System.assertEquals('Prioritized', o.Priority__c, 'opportunity priority');
    }

    @isTest
    public static void test_v2_sets_priority_from_amount() {
        Opportunity o = new Opportunity(
            AccountId = [SELECT Id FROM Account WHERE Industry = 'Mining'].Id,
            Name = 'Expansive Deal',
            CloseDate = Date.today(),
            StageName = 'New',
            Amount = 150000
        );
        OpportunityServiceV2 os = new OpportunityServiceV2();

        os.delegate = new MockQueryDelegate();

        Test.startTest();
        os.updatePriorities_v2(new List<Opportunity>{o}, OpportunityServiceV2.OpportunityMode.MODE_OVERWRITE);
        Test.stopTest();

        System.assertEquals('Prioritized', o.Priority__c, 'opportunity priority');
    }

    @isTest
    public static void test_v2_getAmountPriority() {
        OpportunityServiceV2 os = new OpportunityServiceV2();

        System.assertEquals('Prioritized', os.getAmountPriority(200000), 'high dollar priority');
        System.assertEquals('Normal', os.getAmountPriority(30000), 'medium dollar priority');
        System.assertEquals('Low', os.getAmountPriority(1000), 'low dollar priority');
    }

    @isTest
    public static void test_v2_concrete_delegate() {
        System.assertNotEquals(
            null,
            new OpportunityServiceV2.OppServiceQueryConcreteDelegate().getPriorityMetadata(),
            'org metadata query'
        );
    }
}